# Trading Strategy Configuration
exchange: binance

# Single pair for backwards compatibility
symbols:
  base: ["BTC/USDT", "ETH/USDT"]

# Multiple pairs configuration
pairs:
  - name: "BTC-ETH"
    asset_y: "ETH/USDT"
    asset_x: "BTC/USDT"
    enabled: true

  - name: "SOL-ETH"
    asset_y: "SOL/USDT"
    asset_x: "ETH/USDT"
    enabled: true

  - name: "AVAX-SOL"
    asset_y: "AVAX/USDT"
    asset_x: "SOL/USDT"
    enabled: true

  - name: "MATIC-BNB"
    asset_y: "MATIC/USDT"
    asset_x: "BNB/USDT"
    enabled: true

  - name: "LINK-UNI"
    asset_y: "LINK/USDT"
    asset_x: "UNI/USDT"
    enabled: true

  - name: "DOT-ATOM"
    asset_y: "DOT/USDT"
    asset_x: "ATOM/USDT"
    enabled: true

  # BTC pairs
  - name: "SOL-BTC"
    asset_y: "SOL/USDT"
    asset_x: "BTC/USDT"
    enabled: true

  - name: "AVAX-BTC"
    asset_y: "AVAX/USDT"
    asset_x: "BTC/USDT"
    enabled: true

  - name: "MATIC-BTC"
    asset_y: "MATIC/USDT"
    asset_x: "BTC/USDT"
    enabled: true

  - name: "BNB-BTC"
    asset_y: "BNB/USDT"
    asset_x: "BTC/USDT"
    enabled: true

  - name: "LINK-BTC"
    asset_y: "LINK/USDT"
    asset_x: "BTC/USDT"
    enabled: true

  - name: "UNI-BTC"
    asset_y: "UNI/USDT"
    asset_x: "BTC/USDT"
    enabled: true

  - name: "DOT-BTC"
    asset_y: "DOT/USDT"
    asset_x: "BTC/USDT"
    enabled: true

  - name: "ATOM-BTC"
    asset_y: "ATOM/USDT"
    asset_x: "BTC/USDT"
    enabled: true

  # ETH pairs
  - name: "AVAX-ETH"
    asset_y: "AVAX/USDT"
    asset_x: "ETH/USDT"
    enabled: true

  - name: "MATIC-ETH"
    asset_y: "MATIC/USDT"
    asset_x: "ETH/USDT"
    enabled: true

  - name: "BNB-ETH"
    asset_y: "BNB/USDT"
    asset_x: "ETH/USDT"
    enabled: true

  - name: "LINK-ETH"
    asset_y: "LINK/USDT"
    asset_x: "ETH/USDT"
    enabled: true

  - name: "UNI-ETH"
    asset_y: "UNI/USDT"
    asset_x: "ETH/USDT"
    enabled: true

  - name: "DOT-ETH"
    asset_y: "DOT/USDT"
    asset_x: "ETH/USDT"
    enabled: true

  - name: "ATOM-ETH"
    asset_y: "ATOM/USDT"
    asset_x: "ETH/USDT"
    enabled: true

  # Additional cross-asset pairs (non-BTC/ETH anchors)
  - name: "BNB-SOL"
    asset_y: "BNB/USDT"
    asset_x: "SOL/USDT"
    enabled: true

  - name: "BNB-AVAX"
    asset_y: "BNB/USDT"
    asset_x: "AVAX/USDT"
    enabled: true

  - name: "SOL-MATIC"
    asset_y: "SOL/USDT"
    asset_x: "MATIC/USDT"
    enabled: true

  - name: "SOL-LINK"
    asset_y: "SOL/USDT"
    asset_x: "LINK/USDT"
    enabled: true

  - name: "SOL-UNI"
    asset_y: "SOL/USDT"
    asset_x: "UNI/USDT"
    enabled: true

  - name: "AVAX-MATIC"
    asset_y: "AVAX/USDT"
    asset_x: "MATIC/USDT"
    enabled: true

  - name: "AVAX-LINK"
    asset_y: "AVAX/USDT"
    asset_x: "LINK/USDT"
    enabled: true

  - name: "AVAX-UNI"
    asset_y: "AVAX/USDT"
    asset_x: "UNI/USDT"
    enabled: true

  - name: "MATIC-LINK"
    asset_y: "MATIC/USDT"
    asset_x: "LINK/USDT"
    enabled: true

  - name: "MATIC-UNI"
    asset_y: "MATIC/USDT"
    asset_x: "UNI/USDT"
    enabled: true

  - name: "LINK-DOT"
    asset_y: "LINK/USDT"
    asset_x: "DOT/USDT"
    enabled: true

  - name: "LINK-ATOM"
    asset_y: "LINK/USDT"
    asset_x: "ATOM/USDT"
    enabled: true

  - name: "UNI-DOT"
    asset_y: "UNI/USDT"
    asset_x: "DOT/USDT"
    enabled: true

  - name: "UNI-ATOM"
    asset_y: "UNI/USDT"
    asset_x: "ATOM/USDT"
    enabled: true

  # Fill out remaining combos to reach full 45
  - name: "ATOM-AVAX"
    asset_y: "ATOM/USDT"
    asset_x: "AVAX/USDT"
    enabled: true

  - name: "ATOM-BNB"
    asset_y: "ATOM/USDT"
    asset_x: "BNB/USDT"
    enabled: true

  - name: "ATOM-MATIC"
    asset_y: "ATOM/USDT"
    asset_x: "MATIC/USDT"
    enabled: true

  - name: "ATOM-SOL"
    asset_y: "ATOM/USDT"
    asset_x: "SOL/USDT"
    enabled: true

  - name: "AVAX-DOT"
    asset_y: "AVAX/USDT"
    asset_x: "DOT/USDT"
    enabled: true

  - name: "BNB-DOT"
    asset_y: "BNB/USDT"
    asset_x: "DOT/USDT"
    enabled: true

  - name: "BNB-LINK"
    asset_y: "BNB/USDT"
    asset_x: "LINK/USDT"
    enabled: true

  - name: "BNB-UNI"
    asset_y: "BNB/USDT"
    asset_x: "UNI/USDT"
    enabled: true

  - name: "DOT-MATIC"
    asset_y: "DOT/USDT"
    asset_x: "MATIC/USDT"
    enabled: true

  - name: "DOT-SOL"
    asset_y: "DOT/USDT"
    asset_x: "SOL/USDT"
    enabled: true

timeframe: "1h"

# Signal Generation Windows
windows:
  ols_beta: 200        # Bars for rolling OLS hedge ratio
  zscore: 100          # Bars for z-score calculation

# Entry/Exit Thresholds
thresholds:
  z_in: 2.0            # Enter when |z| > this
  z_out: 0.5           # Exit when |z| < this
  z_stop: 3.5          # Hard stop when |z| > this

# Risk Management
risk:
  target_sigma_usd: 200.0          # P&L per 1.0 z move
  max_notional_usd_per_leg: 25000   # Maximum position per leg
  max_adv_frac: 0.05               # Max fraction of average daily volume

# Cost Assumptions
costs:
  fee_bps: 10          # 0.10% per leg (10 basis points)
  slippage_bps: 5      # 0.05% slippage (5 basis points)

# Filters
filters:
  min_adv_usd: 10000             # Minimum average hourly dollar volume threshold
  max_realized_vol_annual: 2.0     # Maximum annualized volatility
  min_bars_required: 250           # Minimum bars needed to start trading

# Backtesting
backtest:
  initial_capital: 10000
  start_date: null                 # Use null for all available data
  end_date: null
  walk_forward_split: 0.7          # Train/test split ratio

# Notifications
notifications:
  enabled: true
  slack_enabled: true
  telegram_enabled: false
  debounce_minutes: 5              # Minimum time between alerts
  # Email notifications
  email_enabled: true
  email_backend: sendmail          # 'sendmail' or 'smtp'
  sendmail_path: /usr/sbin/sendmail
  email_to:
    - domkav@gmail.com

# Logging
logging:
  level: INFO
  format: json
  file: logs/scanner.log
